type: custom:lovelace-lcars-card
title: USS Enterprise NCC-1701-D
groups:
  - group_id: top-header
    elements:
      - id: top-header
        type: top_header
        text:
          left_content: U.S.S. HERCULES / WILLEMETTE CLASS
          right_content: NCC-1901
          font_weight: bold
          color: "#FFCC00"
        layout:
          width: 100%
          height: 30
          offset_x: 0
          offset_y: 0
          anchor:
            to: container
            element_point: top-left
            target_point: top-left
  - group_id: sub-header
    elements:
      - id: right-endcap
        type: endcap
        appearance:
          fill: "#0099CC"
          direction: right
        layout:
          height: 40
          width: 50
          offset_y: 5
          anchor:
            to: top-header.top-header
            element_point: top-right
            target_point: bottom-right
      - id: header
        type: text
        text:
          content: main
          fill: "#DA9A4D"
          text_anchor: end
          text_transform: uppercase
          font_family: Antonio
          font_weight: bold
        layout:
          height: 40
          offset_x: -5
          anchor:
            to: sub-header.right-endcap
            element_point: top-right
            target_point: top-left
      - id: header-bar
        type: rectangle
        appearance:
          fill: "#0099CC"
        layout:
          offset_x: 5
          anchor:
            to: sub-header.elbow
            element_point: top-left
            target_point: top-right
          stretch:
            target1:
              id: sub-header.header
              edge: left
              padding: -5
            target2:
              id: sub-header.right-endcap
              edge: bottom
      - id: elbow
        type: elbow
        appearance:
          orientation: top-left
          fill: "#0099CC"
        layout:
          body_width: 130
          arm_height: 40
          width: 145
          height: 55
          offset_y: 5
          anchor:
            to: top-header.top-header
            element_point: top-left
            target_point: bottom-left
  - group_id: buttons
    elements:
      - id: environmental
        type: rectangle
        text:
          content: environmental
          font_family: Antonio
          text_transform: uppercase
          text_anchor: end
          font_size: 22
          offset_x: -5
        appearance:
          fill: "#0099CC"
        layout:
          width: 130
          height: 40
          offset_y: 5
          anchor:
            to: sub-header.elbow
            element_point: top-left
            target_point: bottom-left
      - id: sickbay
        type: rectangle
        text:
          content: sickbay
          font_family: Antonio
          text_transform: uppercase
          text_anchor: end
          font_size: 22
          offset_x: -5
        appearance:
          fill: "#0099CC"
        layout:
          width: 130
          height: 40
          offset_y: 5
          anchor:
            to: buttons.environmental
            element_point: top-left
            target_point: bottom-left
      - id: ship_map
        type: rectangle
        text:
          content: ship map
          font_family: Antonio
          text_transform: uppercase
          text_anchor: end
          font_size: 22
          offset_x: -5
        appearance:
          fill: "#0099CC"
        layout:
          width: 130
          height: 40
          offset_y: 5
          anchor:
            to: buttons.sickbay
            element_point: top-left
            target_point: bottom-left
      - id: sensors
        type: rectangle
        text:
          content: sensors
          font_family: Antonio
          text_transform: uppercase
          text_anchor: end
          font_size: 22
          offset_x: -5
        appearance:
          fill: "#0099CC"
        layout:
          width: 130
          height: 40
          offset_y: 5
          anchor:
            to: buttons.ship_map
            element_point: top-left
            target_point: bottom-left
