type: custom:lovelace-lcars-card
title: USS Enterprise NCC-1701-D
groups:
  - group_id: top-header
    elements:
      - id: top-header
        type: top_header
        text:
          left_content: U.S.S. HERCULES / WILLEMETTE CLASS
          right_content: NCC-1901
          fill: "#7addee"
        appearance:
          fill: "#04bfd8"
        layout:
          width: 100%
          height: 30
          offsetX: 0
          offsetY: 5
          anchor:
            to: container
            element_point: topLeft
            target_point: topLeft
  - group_id: sub-header
    elements:
      - id: right-endcap
        type: endcap
        appearance:
          fill: "#3ad9e7"
          direction: right
        layout:
          height: 40
          width: 10%
          offsetY: 10
          anchor:
            to: top-header.top-header
            element_point: topRight
            target_point: bottomRight
      - id: header
        type: text
        text:
          content: evansville • IN
          fill: "#5ca8ea"
          text_anchor: end
          textTransform: uppercase
          fontFamily: Antonio
          fontWeight: bold
        layout:
          height: 40
          offsetX: -5
          anchor:
            to: sub-header.right-endcap
            element_point: topRight
            target_point: topLeft
      - id: header-bar
        type: rectangle
        appearance:
          fill: "#3ad9e7"
        layout:
          offsetX: 5
          anchor:
            to: sub-header.elbow
            element_point: topLeft
            target_point: topRight
          stretch:
            target1:
              id: sub-header.header
              edge: left
              padding: -5
            target2:
              id: sub-header.right-endcap
              edge: bottom
      - id: elbow
        type: elbow
        appearance:
          orientation: top-left
          fill: "#12a4e3"
        layout:
          bodyWidth: 130
          armHeight: 40
          width: 25%
          height: 60
          offsetY: 10
          anchor:
            to: top-header.top-header
            element_point: topLeft
            target_point: bottomLeft
  - group_id: environmental-header
    elements:
      - id: elbow
        type: elbow
        appearance:
          orientation: bottom-left
          fill: "#5ca8ea"
        text:
          content: environmental
          fontFamily: Antonio
          textTransform: uppercase
          elbow_text_position: body
          textAnchor: end
          fontSize: 22
          offsetX: -5
          offsetY: -40
          cutout: true
        layout:
          bodyWidth: 130
          armHeight: 15
          width: 145
          height: 190
          offsetY: 5
          anchor:
            to: sub-header.elbow
            element_point: topLeft
            target_point: bottomLeft
      - id: logger
        type: logger-widget
        text:
          max_lines: 6
          fill: "#FFFFFF"
          text_anchor: start
          fontSize: 22
          textTransform: uppercase
        layout:
          width: 400
          height: 200
          offsetY: 10
          anchor:
            to: sub-header.header-bar
            element_point: topLeft
            target_point: bottomLeft
      - id: bar-1
        type: rectangle
        appearance:
          fill: "#044ea9"
        layout:
          width: 5
          height: 15
          offsetX: 5
          anchor:
            to: environmental-header.elbow
            element_point: bottomLeft
            target_point: bottomRight
          stretch:
            target1:
              id: sub-header.elbow
              edge: right
      - id: bar-2
        type: rectangle
        appearance:
          fill: "#5ca8ea"
        layout:
          width: 10%
          height: 15
          offsetX: 5
          anchor:
            to: environmental-header.bar-1
            element_point: bottomLeft
            target_point: bottomRight
      - id: bar-3
        type: rectangle
        appearance:
          fill: "#86c8ff"
        layout:
          width: 25%
          height: 15
          offsetX: 5
          anchor:
            to: environmental-header.bar-2
            element_point: bottomLeft
            target_point: bottomRight
      - id: bar-4
        type: rectangle
        appearance:
          fill: "#12a4e3"
        layout:
          width: 40
          height: 15
          offsetX: 5
          anchor:
            to: environmental-header.bar-3
            element_point: bottomLeft
            target_point: bottomRight
          stretch:
            target1:
              id: container
              edge: right
      - id: current-condition-widget
        type: entity-text-widget
        entity: weather.openweathermap
        appearance:
          fill: "#5ca8ea"
        label:
          fontFamily: Antonio
          content: current conditions
        value:
          fontFamily: Antonio
          fill: "#3ad9e7"
          textTransform: lowercase
        layout:
          height: 25
          offsetY: -160
          anchor:
            to: environmental-header.bar-3
            element_point: bottomLeft
            target_point: topRight
      - id: current-temp-widget
        type: entity-text-widget
        entity:
          - sensor.openweathermap_temperature
          - sensor.openweathermap_feels_like_temperature
        appearance:
          fill: "#12a4e3"
        label:
          fontFamily: Antonio
          content: Temperature (feel)
        value:
          fontFamily: Antonio
          fill: "#5ca8ea"
        layout:
          height: 25
          offsetY: 5
          anchor:
            to: environmental-header.current-condition-widget
            element_point: topLeft
            target_point: bottomLeft
      - id: precipitation-chance-widget
        type: entity-text-widget
        entity: weather.kevv_daynight
        appearance:
          fill: "#12a4e3"
        label:
          fontFamily: Antonio
          content: precipitation chance
        value:
          fontFamily: Antonio
          content: "-50%"
          fill: "#5ca8ea"
        layout:
          height: 25
          offsetY: 5
          anchor:
            to: environmental-header.current-temp-widget
            element_point: topLeft
            target_point: bottomLeft
      - id: uv-index-widget
        type: entity-text-widget
        entity: weather.home
        attribute: uv_index
        appearance:
          fill: "#225782"
        label:
          fontFamily: Antonio
          content: Uv index
        value:
          fontFamily: Antonio
          fill: "#044ea9"
        layout:
          height: 25
          offsetY: 5
          anchor:
            to: environmental-header.precipitation-chance-widget
            element_point: topLeft
            target_point: bottomLeft
      - id: air-quality-index-widget
        type: entity-text-widget
        entity: weather.kevv_daynight
        appearance:
          fill: "#225782"
        label:
          fontFamily: Antonio
          content: Air Quality index
        value:
          fontFamily: Antonio
          content: "100"
          fill: "#044ea9"
        layout:
          height: 25
          offsetY: 5
          anchor:
            to: environmental-header.uv-index-widget
            element_point: topLeft
            target_point: bottomLeft
      - id: wind-widget
        type: entity-text-widget
        entity:
          - sensor.kevv_wind_speed
          - sensor.openweathermap_wind_bearing
        appearance:
          fill: "#04bfd8"
        label:
          fontFamily: Antonio
          content: Wind Speed (direction))
        value:
          fontFamily: Antonio
          fill: "#04bfd8"
        layout:
          height: 25
          offsetY: 5
          anchor:
            to: environmental-header.air-quality-index-widget
            element_point: topLeft
            target_point: bottomLeft
  - group_id: environmental-buttons
    elements:
      - id: main
        type: elbow
        text:
          content: main
          fontFamily: Antonio
          textTransform: uppercase
          textAnchor: end
          fontSize: 22
          offsetX: -5
          offsetY: 18
          elbow_text_position: body
          fill: "#000000"
        appearance:
          fill:
            hover: "#00CCFF"
            default: "#00ffff"
            active: "#0066AA"
            orientation: top-left
        layout:
          bodyWidth: 130
          armHeight: 15
          width: 145
          height: 80
          offsetY: 10
          anchor:
            to: environmental-header.elbow
            element_point: topLeft
            target_point: bottomLeft
      - id: sickbay
        type: rectangle
        text:
          content: sickbay
          fontFamily: Antonio
          textTransform: uppercase
          textAnchor: end
          fontSize: 22
          offsetX: -5
          fill: "#000000"
        appearance:
          fill:
            hover: "#00CCFF"
            default: "#7addee"
            active: "#0066AA"
        layout:
          width: 130
          height: 40
          offsetY: 5
          anchor:
            to: environmental-buttons.main
            element_point: topLeft
            target_point: bottomLeft
      - id: ship_map
        type: rectangle
        text:
          content: ship map
          fontFamily: Antonio
          textTransform: uppercase
          textAnchor: end
          fontSize: 22
          offsetX: -5
          fill: "#000000"
        appearance:
          fill:
            hover: "#00CCFF"
            default: "#9ec9ce"
            active: "#0066AA"
        layout:
          width: 130
          height: 40
          offsetY: 5
          anchor:
            to: environmental-buttons.sickbay
            element_point: topLeft
            target_point: bottomLeft
      - id: sensors
        type: rectangle
        text:
          content: sensors
          fontFamily: Antonio
          textTransform: uppercase
          textAnchor: end
          fontSize: 22
          offsetX: -5
          fill: "#000000"
        appearance:
          fill:
            hover: "#00CCFF"
            default: "#9ec9ce"
            active: "#0066AA"
        layout:
          width: 130
          height: 40
          offsetY: 5
          anchor:
            to: environmental-buttons.ship_map
            element_point: topLeft
            target_point: bottomLeft
        button:
          enabled: true
          actions:
            tap:
              action: toggle
              entity: input_boolean.message_logger_debug_toggle
  - group_id: environmental-lower-section
    elements:
      - id: bar-1
        type: rectangle
        appearance:
          fill: "#7addee"
        layout:
          width: 35%
          height: 15
          offsetX: 5
          anchor:
            to: environmental-buttons.main
            element_point: topLeft
            target_point: topRight
      - id: bar-2
        type: rectangle
        appearance:
          fill: "#7addee"
        layout:
          height: 15
          offsetX: 5
          anchor:
            to: environmental-lower-section.bar-1
            element_point: topLeft
            target_point: topRight
          stretch:
            target1:
              id: environmental-lower-section.elbow
              edge: left
              padding: -5
      - id: elbow
        type: elbow
        appearance:
          fill: "#7addee"
          orientation: top-right
        layout:
          bodyWidth: 80
          armHeight: 15
          width: 320
          height: 80
          offsetX: 5
          offsetY: 10
          anchor:
            to: environmental-header.bar-4
            element_point: topRight
            target_point: bottomRight
          stretch:
            target1:
              id: container
              edge: bottom
      - id: graph
        type: graph-widget
        entity:
          - id: sensor.living_room_temperature
            duration: 2000
          - id: sensor.kevv_temperature
            duration: 2000
          - id: sensor.living_room_humidity
            duration: 3000
          - id: sensor.kevv_relative_humidity
            duration: 3000
        layout:
          width: 500
          height: 150
          offsetY: 20
          anchor:
            to: environmental-lower-section.bar-1
            element_point: topLeft
            target_point: bottomLeft
      - id: weather
        type: weather-icon
        entity: weather.openweathermap
        layout:
          width: 210
          height: 210
          offsetY: 5
          anchor:
            to: environmental-header.bar-1
            element_point: bottomCenter
            target_point: topCenter
      - id: sliders
        type: vertical-slider
        entity:
          - id: climate.living_room
            attribute: target_temp_high
            label: high
            color: "#044ea9"
          - id: climate.living_room
            attribute: target_temp_low
            label: low
          - id: sensor.living_room_temperature
            label: current
        grid:
          num_lines: 15
        spacing: 14
        top_padding: 6
        label_height: 50
        layout:
          offsetY: 25
          width: 220
          height: 200
          anchor:
            to: environmental-lower-section.elbow
            element_point: topLeft
            target_point: topLeft
  - group_id: metric-widgets
    elements:
      - id: widget1
        type: entity-metric-widget
        entity: sensor.kevv_wind_speed
        appearance:
          rounded: right
        layout:
          offsetY: 10
          anchor:
            to: environmental-lower-section.bar-2
            element_point: topRight
            target_point: bottomRight
        value:
          fontWeight: bold
      - id: widget2
        type: entity-metric-widget
        entity: sensor.openweathermap_cloud_coverage
        appearance:
          rounded: right
        layout:
          offsetY: 30
          anchor:
            to: metric-widgets.widget1
            element_point: topLeft
            target_point: bottomLeft
      - id: widget3
        type: entity-metric-widget
        entity: sensor.openweathermap_dew_point_temperature
        appearance:
          rounded: right
        layout:
          offsetY: 30
          anchor:
            to: metric-widgets.widget2
            element_point: topLeft
            target_point: bottomLeft
