type: custom:lovelace-lcars-card
title: USS Enterprise NCC-1701-D
groups:
  - group_id: top-header
    elements:
      - id: top-header
        type: top_header
        text:
          left_content: U.S.S. HERCULES / WILLEMETTE CLASS
          right_content: NCC-1901
          fontWeight: bold
          color: "#FFCC00"
        layout:
          width: 100%
          height: 30
          offsetX: 0
          offsetY: 0
          anchor:
            to: container
            element_point: topLeft
            target_point: topLeft
  - group_id: sub-header
    elements:
      - id: right-endcap
        type: endcap
        appearance:
          fill: "#0099CC"
          direction: right
        layout:
          height: 40
          width: 50
          offsetY: 5
          anchor:
            to: top-header.top-header
            element_point: topRight
            target_point: bottomRight
      - id: header
        type: text
        text:
          content: main
          fill: "#DA9A4D"
          text_anchor: end
          textTransform: uppercase
          fontFamily: Antonio
          fontWeight: bold
        layout:
          height: 40
          offsetX: -5
          anchor:
            to: sub-header.right-endcap
            element_point: topRight
            target_point: topLeft
      - id: header-bar
        type: rectangle
        appearance:
          fill: "#0099CC"
        layout:
          offsetX: 5
          anchor:
            to: sub-header.elbow
            element_point: topLeft
            target_point: topRight
          stretch:
            target1:
              id: sub-header.header
              edge: left
              padding: -5
            target2:
              id: sub-header.right-endcap
              edge: bottom
      - id: elbow
        type: elbow
        appearance:
          orientation: top-left
          bodyWidth: 130
          armHeight: 40
          fill: "#0099CC"
        layout:
          width: 145
          height: 55
          offsetY: 5
          anchor:
            to: top-header.top-header
            element_point: topLeft
            target_point: bottomLeft
  - group_id: buttons
    elements:
      - id: environmental
        type: rectangle
        text:
          content: environmental
          fontFamily: Antonio
          textTransform: uppercase
          textAnchor: end
          fontSize: 22
          offsetX: -5
        appearance:
          fill: "#0099CC"
        layout:
          width: 130
          height: 40
          offsetY: 5
          anchor:
            to: sub-header.elbow
            element_point: topLeft
            target_point: bottomLeft
      - id: sickbay
        type: rectangle
        text:
          content: sickbay
          fontFamily: Antonio
          textTransform: uppercase
          textAnchor: end
          fontSize: 22
          offsetX: -5
        appearance:
          fill: "#0099CC"
        layout:
          width: 130
          height: 40
          offsetY: 5
          anchor:
            to: buttons.environmental
            element_point: topLeft
            target_point: bottomLeft
      - id: ship_map
        type: rectangle
        text:
          content: ship map
          fontFamily: Antonio
          textTransform: uppercase
          textAnchor: end
          fontSize: 22
          offsetX: -5
        appearance:
          fill: "#0099CC"
        layout:
          width: 130
          height: 40
          offsetY: 5
          anchor:
            to: buttons.sickbay
            element_point: topLeft
            target_point: bottomLeft
      - id: sensors
        type: rectangle
        text:
          content: sensors
          fontFamily: Antonio
          textTransform: uppercase
          textAnchor: end
          fontSize: 22
          offsetX: -5
        appearance:
          fill: "#0099CC"
        layout:
          width: 130
          height: 40
          offsetY: 5
          anchor:
            to: buttons.ship_map
            element_point: topLeft
            target_point: bottomLeft
